### ISSUE TITLE
Can you have the pop-up boxes explain more about what's going to happen?

### ISSUE THREAD

**Issue by oakesrandall** [SpindleMonkey/project-1#1]
I know what's about to happen because you've told me, but if I was playing at home I might need more explanation.  "X player is about to be sent to the other side, if they make it through, x happens...otherwise...etc"

**Comment by SpindleMonkey** [comment]
I didn't want to muddy up the modals with more text so I added game instructions to the landing page, modified the wording for the "you get to pick one of the defense team's members to add to your team" a bit, and added a '*' to the team that started the round (and a note at the bottom). Hopefully this now explains the game flow for somebody who has never played before.
